### ISSUE TITLE
XMLSec::SigningError: signature failed on OS X

### ISSUE THREAD

**Issue by monfresh** [awong-dev/nokogiri-xmlsec-me-harder#4]
Hey Albert,

On OS X, we're getting `XMLSec::SigningError: signature failed` when `sign_with_certificate` is called. This doesn't happen on Ubuntu. Do you know why this fails on OS X and how to fix it? Thanks!

Here's the stack trace:

```
 Failure/Error: Unable to find matching line from backtrace
     XMLSec::SigningError:
       signature failed, XmlSec error: func=xmlSecXPathDataExecute:file=xpath.c:line=273:obj=(null):subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('_01e3fd50-aa50-0132-fe86-00e6501b8d64'))
       func=xmlSecXPathDataListExecute:file=xpath.c:line=373:obj=(null):subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed:
       func=xmlSecTransformXPathExecute:file=xpath.c:line=483:obj=xpointer:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed:
       func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2405:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed:
       func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1236:obj=(null):subj=xmlSecTransformPushXml:error=1:xmlsec library function failed:transform=xpointer
       func=xmlSecTransformCtxExecute:file=transforms.c:line=1296:obj=(null):subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed:
       func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1571:obj=(null):subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed:
       func=xmlSecDSigCtxProcessSignedInfoNode:file=xmldsig.c:line=804:obj=(null):subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed:node=Reference
       func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=547:obj=(null):subj=xmlSecDSigCtxProcessSignedInfoNode:error=1:xmlsec library function failed:
       func=xmlSecDSigCtxSign:file=xmldsig.c:line=303:obj=(null):subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed:
     # /Users/moncefbelyamani/.rvm/gems/ruby-2.1.5@save-ferris/gems/nokogiri-xmlsec-me-harder-0.9.1/lib/xmlsec.rb:18:in `sign_with_certificate'
     # /Users/moncefbelyamani/.rvm/gems/ruby-2.1.5@save-ferris/gems/nokogiri-xmlsec-me-harder-0.9.1/lib/xmlsec.rb:18:in `sign!'
```

**Comment by awong-dev** [comment]
There's a version skew problem between xmlsec and libxml2 on homebroew in
mac. I don't know how to fix yet..I bet if we got the xmlsec maintainer to
recomplie against the version of libxml2 that nokogiri uses, it'd resolve
the problem.

For me to work around locally, I custom built both libxml2 and xmlsec1 but
that's pretty heavy weight.

On Wed, Mar 11, 2015 at 12:14 PM, Moncef Belyamani <notifications@github.com
